osx_image: xcode9.4
language: objective-c

cache:
  directories:
    - Carthage

before_install:
  - brew update
  - brew outdated carthage || brew upgrade carthage
  - brew install swiftlint || true
  - travis_wait 35; bin/bootstrap-if-needed

script:
  - set -o pipefail && xcodebuild -project Malibu.xcodeproj -scheme "Malibu-macOS" -sdk macosx clean build
  - set -o pipefail && xcodebuild -project Malibu.xcodeproj -scheme "Malibu-macOS" -sdk macosx -enableCodeCoverage YES test
  - set -o pipefail && xcodebuild -project Malibu.xcodeproj -scheme "Malibu-iOS" -sdk iphonesimulator -destination name="iPhone 8" clean build
  - set -o pipefail && xcodebuild -project Malibu.xcodeproj -scheme "Malibu-iOS" -sdk iphonesimulator -destination name="iPhone 8" -enableCodeCoverage YES test
  - set -o pipefail && xcodebuild -project Malibu.xcodeproj -scheme "Malibu-tvOS" -destination 'platform:tvOS Simulator, OS:11.4, name:Apple TV' clean build
  - set -o pipefail && xcodebuild -project Malibu.xcodeproj -scheme "Malibu-tvOS" -destination 'platform:tvOS Simulator, OS:11.4, name:Apple TV' -enableCodeCoverage YES test

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false
